security:
    password_hashers:
        App\Entity\User\Admin: auto
        App\Entity\User\User: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user 
        # from session & other features (e.g. switch_user)
        app_admin_provider:
            entity:
                class: App\Entity\User\Admin
                property: username

        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: phone
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_firewall:
            pattern: ^/api
            provider: app_user_provider

        admin_firewall:
            pattern: ^/admin
            lazy: true
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                default_target_path: app_admin_login
            provider: app_admin_provider
            logout:
                path: app_admin_logout

        user_firewall:
            pattern: ^/
            lazy: true
            form_login:
                login_path: app_user_login
                check_path: app_user_login
                default_target_path: admin
            provider: app_user_provider
            logout:
                path: app_user_logout

    access_control:
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/profile$, roles: ROLE_USER }
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
