services:
    nginx:
        image: nginx:1.25.3-alpine-slim
        container_name: app-nginx
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/app
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - 80:80
    app:
        build:
            context: .
            dockerfile: ./config/php/Dockerfile
        container_name: app-php
        ports:
            - '9000:9000'
        restart: unless-stopped
        volumes:
            - ./src:/var/www/app