version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=app
    ports:
      - '4306:3306'
    volumes:
      - mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

volumes:
  mysql:
