name: Sync and deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_APP_ENV: prod
        envkey_APP_SECRET: ${{ secrets.ENV_SECRET }}
        envkey_CORS_ALLOW_ORIGIN: "*"
        file_name: .env

    - name: Sync
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ''
        rm: false
        source: "./"
        target: ${{ secrets.DEPLOY_PWD }}
    
    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        command_timeout: 200m
        script: |
          cd ${{ secrets.DEPLOY_PWD }}
          ls -la
          composer install
          bin/console doctrine:schema:update --force
          bin/console --no-interaction assets:install
          bin/console --no-interaction cache:clear
          npm install
          npm run build
          cd ..
          chown -R www-data:www-data dev